apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: default
data:
  APP_ENV: "development"
  LOG_LEVEL: "INFO"
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "massapplyapp"
  S3_ENDPOINT_URL: "https://massapplyapp.s3.us-east-1.amazonaws.com"
  RATE_LIMIT_ENABLED: "True"
  RATE_LIMIT_PER_MINUTE: "60"
  CORS_ORIGINS: '["http://localhost:3000", "http://localhost:5173", "http://frontend:3000", "http://0.0.0.0:3000"]'
