apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: default
data:
  APP_ENV: "development"
  LOG_LEVEL: "INFO"
  AWS_REGION: "us-east-1"
  CORS_ORIGINS: '["http://localhost:3000", "http://localhost:5173", "http://frontend:3000", "http://0.0.0.0:3000"]'