apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: default
data:
  APP_ENV: "development"
  LOG_LEVEL: "INFO"
  AWS_REGION: "us-east-1"
  RATE_LIMIT_ENABLED: "True"
  RATE_LIMIT_PER_MINUTE: "60"
  CORS_ORIGINS: '["http://localhost:3000", "http://localhost:5173", "http://frontend:3000", "http://0.0.0.0:3000"]'
  PRODUCT_SERVICE_URL: "http://product-service:8000"
