name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Make Docker build script executable
      - name: Make Script Executable
        run: chmod +x dockerBuilder.sh

      # 5. Build and push Docker images
      - name: Build and push Docker images
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: ./dockerBuilder.sh

      # 6. Setup SSH for CD
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.10.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 7. Run deployment script on EC2
      - name: Deploy to k3s
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@44.197.181.153 << 'EOF'
            # Optional: pull latest manifests if using git on the server
            cd ~/deployment-script
            # git pull origin development

            # Run the deployment script
            bash ~/deployment.sh
          EOF
